sample/build.gradle
Adds `transitive = true` to library dependency in the sample app `build.gradle` file. This alleviates the need to declare transitive dependencies such as Tangram to make the API directly available in the app.
=> Include library transitive dependencies in sample app

library/src/main/java/com/mapzen/android/MapFragment.java, library/src/main/java/com/mapzen/android/MapInitializer.java, library/src/main/java/com/mapzen/android/MapView.java, library/src/main/java/com/mapzen/android/MapzenMap.java, library/src/main/java/com/mapzen/android/OnMapReadyCallback.java, library/src/main/java/com/mapzen/android/TangramMapView.java, library/src/main/res/layout/view_map.xml, library/src/test/java/com/mapzen/android/MapFragmentTest.java, library/src/test/java/com/mapzen/android/MapInitializerTest.java, library/src/test/java/com/mapzen/android/MapViewTest.java, library/src/test/java/com/mapzen/android/MapzenMapTest.java, library/src/test/java/com/mapzen/android/OverlayManagerTest.java, library/src/test/java/com/mapzen/android/TestCallback.java, library/src/test/java/com/mapzen/android/TestMapController.java, library/src/test/java/com/mapzen/android/TestMapView.java, library/src/test/java/com/mapzen/android/TestTangramMapView.java, sample/build.gradle, sample/src/main/java/com/mapzen/android/sample/BasicMapzenActivity.java, sample/src/main/java/com/mapzen/android/sample/MarkerMapzenActivity.java, sample/src/main/java/com/mapzen/android/sample/PolygonMapzenActivity.java, sample/src/main/java/com/mapzen/android/sample/PolylineMapzenActivity.java
Adds `MapzenMap` wrapper for `MapController`.
TODO: Make `OverlayManager` a member of `MapzenMap` to provide a single class API for all common map operations including markers and overlays. Add wrapper methods for common `MapController` methods. Add ability to switch between bundled stylesheets.
=> Adds MapzenMap

circle.yml, library/build.gradle
Replaces `assembleDebug` with `compileDebugSources` on Circle CI.
This way we can still detect compile errors in the sample app but avoid the dreaded `transformClassesWithDexForDebug` which spawns a ridiculous number of threads (4 per library) and eats up all the memory allocated to the container causing the build to intermittently fail. Nom Nom.
* Adds `compileDebugSources` to Gradle verify task
* Removes `assembleDebug` from `circle.yml` test tasks
=> Circle CI updates

library/src/main/java/com/mapzen/android/MapzenMap.java, library/src/main/java/com/mapzen/android/OverlayManager.java, library/src/test/java/com/mapzen/android/MapzenMapTest.java, library/src/test/java/com/mapzen/android/OverlayManagerTest.java, library/src/test/java/com/mapzen/android/TestMapController.java, library/src/test/java/com/mapzen/tangram/TestMapData.java, sample/src/main/AndroidManifest.xml, sample/src/main/java/com/mapzen/android/sample/DroppedPinActivity.java, sample/src/main/java/com/mapzen/android/sample/RouteLineActivity.java, sample/src/main/java/com/mapzen/android/sample/RoutePinsActivity.java, sample/src/main/java/com/mapzen/android/sample/SampleDetailsList.java, sample/src/main/java/com/mapzen/android/sample/SearchResultsActivity.java, sample/src/main/res/layout/activity_clear_btn.xml, sample/src/main/res/layout/activity_pins.xml, sample/src/main/res/values/strings.xml
Adds support for common routing actions in preparation for the EM migration
=> Add routing overlay methods

library/src/main/java/com/mapzen/android/OverlayManager.java, library/src/test/java/com/mapzen/android/OverlayManagerTest.java
Map position is no longer automatically updated when the current location layer is enabled. Instead the position is set only when the user clicks the find me button. Showing the current location marker is now decoupled from centering the map on the current location.
In addition clicking the find me button will zoom the map to a default zoom level (16).
This patch also adds unit test for the find me button click handler.
=> Update my location layer

library/src/main/java/com/mapzen/android/MapzenRouter.java, library/src/main/java/com/mapzen/android/OverlayManager.java, library/src/test/java/com/mapzen/android/MapzenRouterTest.java, sample/src/main/AndroidManifest.xml, sample/src/main/java/com/mapzen/android/sample/RouterActivity.java, sample/src/main/java/com/mapzen/android/sample/SampleDetailsList.java, sample/src/main/res/layout/activity_route.xml, sample/src/main/res/values/mapzen.xml, sample/src/main/res/values/strings.xml
Creates `MapzenRouter` to handle routing functionality
- Handles key management for mapzen.xml with key resource named "turn_by_turn_key"
- Allows for setting of key in code
- Provides access to underlying `Router` for more custom interaction (like setting request log levels)
- Adds example activity to demonstrate router's use
Closes #90
=> Add route key management

config/checkstyle/checkstyle-suppressions.xml, library/src/main/java/com/mapzen/android/MapzenMap.java, library/src/main/java/com/mapzen/android/OverlayManager.java, library/src/main/res/drawable/mz_find_me.xml, library/src/test/java/com/mapzen/android/MapzenMapTest.java, library/src/test/java/com/mapzen/android/OverlayManagerTest.java, library/src/test/java/com/mapzen/android/TestPanResponder.java, library/src/test/java/com/mapzen/tangram/TestMapData.java
Tap to activate find me button. While activated map will remain centered on current location. Tap again or pan map to deactivate.
* Removes `locationRequested` boolean flag from `OverlayManager`.
* Adds activated state to find me button.
* Center map on location update only if find me is active.
* Un-mock class under test in `OverlayManagerTest`.
* Re-restrict scope on private constant value `NAME_CURRENT_LOCATION`.
* Suppress visibility modifier checkstyle check for test classes.
* Moves inner test classes to bottom of `MapzenMapTest`.
* Adds internal pan responder to `MapzenMap`.
* Forwards pan and fling events to both external listener and `OverlayManager`.
* Deactivates find me button on map pan or fling.
Closes https://github.com/mapzen/eraser-map/issues/536
=> Stateful find me button

library/src/main/java/com/mapzen/android/MapzenDistanceFormatter.java, library/src/main/java/com/mapzen/android/MapzenRouter.java, library/src/main/java/com/mapzen/android/TurnByTurnHttpHandler.java, library/src/main/java/com/mapzen/android/dagger/AndroidModule.java, library/src/main/java/com/mapzen/android/dagger/DependencyInjector.java, library/src/main/java/com/mapzen/android/model/Converter.java, library/src/test/java/com/mapzen/android/MapzenRouterTest.java, sample/src/main/java/com/mapzen/android/sample/RouterActivity.java, sample/src/main/res/values/strings.xml
- Migrates `MapzenRouter` to use on-the-road's new `HttpHandler` when setting api key
Depends on: https://github.com/mapzen/on-the-road/pull/73
=> Set httphandler in MapzenRouter constructor

build.gradle
Load maven local dependencies before central or sonatype snapshot repo.
=> Update dependency repos for local testing

.gitmodules
Fixes ability to clone submodules for some (read: my) configurations. I'm not totally sure how the 'git@github.com:' URL is supposed to work, feel free to re-educate me about git practices.
=> Replace 'git@github.com:' with 'https://github.com/' in submodule URLs

sample/build.gradle, sample/src/main/java/com/mapzen/android/sample/RouterActivity.java
Adds option to set sample app API keys in Gradle properties. Prefers turn by turn API key in BuildConfig.java if present.
Closes #126
=> Set sample app API keys in gradle props

docs/index.md, library/build.gradle, library/src/main/java/com/mapzen/android/ApiKeyConstants.java, library/src/main/java/com/mapzen/android/MapzenMapPeliasLocationProvider.java, library/src/main/java/com/mapzen/android/MapzenSearch.java, library/src/main/java/com/mapzen/android/SearchInitializer.java, library/src/main/java/com/mapzen/android/SearchRequestHandler.java, library/src/main/java/com/mapzen/android/dagger/AndroidModule.java, library/src/main/java/com/mapzen/android/dagger/DependencyInjector.java, library/src/test/java/com/mapzen/android/MapzenSearchTest.java, library/src/test/java/com/mapzen/android/SearchInitializerTest.java, library/src/test/java/com/mapzen/android/SearchRequestHandlerTest.java, sample/src/main/AndroidManifest.xml, sample/src/main/java/com/mapzen/android/sample/MapzenSearchViewActivity.java, sample/src/main/java/com/mapzen/android/sample/SampleDetailsList.java, sample/src/main/res/layout/activity_search.xml, sample/src/main/res/values/mapzen.xml, sample/src/main/res/values/strings.xml
- Adds `MapzenSearch` to SDK for interaction with `Pelias` and configuration of related api key
- Adds `MapzenSearchViewActivity` to demonstrate use of `MapzenSearch` using `PeliasSearchView` and `MapzenMap`
Depends on: https://github.com/pelias/pelias-android-sdk/pull/44
Closes #145
=> Add Pelias to SDK and include example Activity

gradle.properties, library/build.gradle, release-checklist.md
* Adds release plugin to `build.gradle`.
* Sets path to `gradle.properties`.
* Adds `version` property used by gradle release plugin.
* Syncs `VERSION_NAME` property used by android-maven plugin and gradle-mvn-push.gradle.
* Triggers `uploadArchives` after successful release build.
https://github.com/researchgate/gradle-release
Closes #157
=> Adds Gradle Release plugin

library/src/main/java/com/mapzen/android/graphics/MapInitializer.java, library/src/test/java/com/mapzen/android/graphics/MapViewTest.java
This commit fixes a bug where an explicitly passed style would not be set on the map. Now, calls to `MapView#getMapAsync(MapStyle, OnMapReadyCallback)` and `MapView#getMapAsync(String, MapStyle, OnMapReadyCallback) will overwrite the `MapStateManager`'s cached map state.
Closes #160
=> Allow explicitly setting the style to override MapStateManager style

library/build.gradle
This will ensure that new users and users who already had the sdk installed and pull the latest (which now includes walkabout) will update their submodules.
=> Check presence of walkabout style instead of bubble-wrap in submodules task

circle.yml, library/build.gradle, library/src/main/java/com/mapzen/android/graphics/TileHttpHandler.java, sample/src/main/java/com/mapzen/android/sample/BasicMapzenActivity.java
Adds gradle tasks and adb log output to get various metrics:
- aar size
`./gradlew aarSize`
- number of methods
`./gradlew countReleaseDexMethods`
- view dependency tree
`./gradlew library:dependencies --configuration compile`
- view required permissions
`./gradlew permissions`
- map load time
`adb logcat -s BasicMapzenActivity`
- cached / non-cached tile load times
`adb logcat -s TileHttpHandler` (must enable logging by modifying value of `DEBUG_REQUESTS` in `TileHttpHandler`)
Newly added gradle tasks are run each time master is built
TODO:
- task to analyze unused dependencies (https://github.com/mapzen/android/issues/186)
Closes #164
=> add metrics

docs/getting-started.md, docs/search.md, docs/turn-by-turn.md, library/src/main/java/com/mapzen/android/core/AndroidModule.java, library/src/main/java/com/mapzen/android/core/ApiKeyConstants.java, library/src/main/java/com/mapzen/android/search/SearchInitializer.java, sample/src/main/res/values/mapzen.xml
- Removes individual service api keys and replaces them with support for unified Mapzen api keys
- Updates documentation
- Replace api resource names with "api_key" in mapzen.xml
Closes #183
=> unified api key

library/build.gradle
Update Lost to snapshot that doesnt require BT permission in SettingsApi
=> Lost 2.0.1-SNAPSHOT

.gitmodules, sample/src/main/java/com/mapzen/android/sample/SwitchStyleActivity.java, sample/src/main/res/values/strings.xml
Temporarily removing Tron 2.0 style due to incompatibilities with Android's `AssetManager`.
The new Tron stylesheet and Blocks submodule rely on relative import paths to load modular resources. Unfortunately loading assets via relative paths is not supported by the `AssetManager`.
```yaml
import:
- ../blocks/functions/zoom.yaml
- ../blocks/functions/pulse.yaml
- ../blocks/geometry/dynamic-width.yaml
- ../blocks/geometry/dynamic-height.yaml
```
https://github.com/tangrams/tron-style/blob/gh-pages/styles/common.yaml#L1-L5
Supporting this version of Tron will require normalizing paths in Tangram ES or finding an alternate way to load imported stylesheets.
Another possibility would be switching from bundled submodules to remote stylesheets distrubuted by the CDN but this is not yet officially …
=> Removes tron style

library/src/main/java/com/mapzen/android/graphics/OverlayManager.java, library/src/main/java/com/mapzen/android/graphics/PersistableMapData.java, library/src/test/java/com/mapzen/android/graphics/OverlayManagerTest.java, library/src/test/java/com/mapzen/tangram/TestMapData.java
Fixes bug where more than one instance of the current location layer would be persisted leading to inconsistent results when map data state is restored.
When current location layer is disabled all instances of `DataLayerType.CURRENT_LOCATION` are removed from `MapDataManager`. This prevents the situation where more than one current location layer is persisted, some with `PersistableMapData.locationEnabled` set to `true` and others `false`.
This change set also reduces the scope of `PersistableMapData` constructors to package local since this class is only intended to be used internally and adds javadoc descriptions for constructor params.
Closes https://github.com/mapzen/eraser-map/issues/753
=> Disable current location layer should remove persisted map data

circle.yml
This change adds Android docs to Mapzen’s docs pipeline, so that successful master commits here trigger a fresh documentation publish process and no one needs to wait for docs to go live.
A new deployment rule tickles [`mapzen/mapzen-docs-generator` CircleCI](https://circleci.com/gh/mapzen/mapzen-docs-generator), which causes the most-recent successful master build to be re-run. If it succeeds, new Android docs will be released to immediately.
Part of https://github.com/mapzen/mapzen-docs-generator/issues/224.
=> Added Circle Tickler to CI config file to join the docs pipeline

library/src/main/java/com/mapzen/android/location/LocationFactory.java, library/src/test/java/com/mapzen/android/location/LocationFactoryTest.java
Deprecates `LocationFactory.sharedClient` and fixes bug due to stale `Context`. 
Deprecates `LocationFactory.sharedClient`. This should no longer be used outside the Mapzen SDK since Lost has proper support for multiple location clients. Apps should instead create their own location client if needed.
Ensures a new `LostApiClient` is created for a new `Context`. Re-using a shared client with a stale `Context` was causing the fused location service to fail to bind and the my location layer to break.
Fixes #229
=> Deprecates `LocationFactory.sharedClient` and fixes bug due to stale `Context`

core/build.gradle, mapzen-android-sdk/build.gradle, mapzen-android-sdk/src/main/java/com/mapzen/android/routing/TurnByTurnHttpHandler.java, mapzen-android-sdk/src/main/java/com/mapzen/android/search/MapzenSearch.java, mapzen-android-sdk/src/test/java/com/mapzen/android/search/MapzenSearchTest.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/AutocompletePendingResult.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/AutocompletePendingResultTest.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/MapzenSearchViewActivity.java
Upgrades search and routing dependencies to use okhttp3 and retrofit2.
Update Pelias Android SDK to version 1.1.0-SNAPSHOT and On the Road to 1.2.0-SNAPSHOT. Both libraries have been updated to use okhttp3 and retrofit2 (see below). Makes all necessary changes in the Mapzen SDK to remain compatible with library public APIs.
https://github.com/pelias/pelias-android-sdk/pull/55
https://github.com/mapzen/on-the-road_android/pull/98
=> Upgrades search and routing to okhttp3 and retrofit2

mapzen-places-api/src/main/java/com/mapzen/places/api/AutocompleteFilter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteController.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompletePresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteView.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceIntentConsts.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceAutocomplete.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceAutocompleteFragment.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceAutocompleteView.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlacePicker.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceSelectionListener.java, mapzen-places-api/src/main/res/layout/place_autocomplete_fragment.xml, mapzen-places-api/src/main/res/layout/place_autocomplete_view.xml, mapzen-places-api/src/main/res/layout/place_picker_activity.xml, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlaceAutocompletePresenterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java
This adds more functionality to the `PlaceAutocomplete` API. Developers can set a bounding box to limit autocomplete results and use the static methods in `PlaceAutocomplete` to launch the autocomplete activity and retrieve place results. This also integrates the autocomplete UI into the `PlacePicker` UI.
The autocomplete search view has been refactored into `PlaceAutocompleteView`. `AutocompleteFilter` is now `Parcelable` so that it can be passed as an intent extra. `PlaceAutocompleteActivity` respects any `BoundingBox` set. The autocomplete fragment and presenter are now passing around a proper `Place` object and there is a `PlaceSelectionListener` to handle notifying relevant objects when a `Place` has been selected from the autocomplete fragment.
There will be a follow up PR with more …
=> Places Autocomplete (part 2)

core/build.gradle, mapzen-places-api/src/main/java/com/mapzen/places/api/AutocompleteFilter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/Place.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/AutocompleteDetailFetchListener.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/AutocompletePendingResult.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/FilterMapper.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/OnPlaceDetailsFetchedListener.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasFilterMapper.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasPlaceDetailFetcher.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteController.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompletePresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteView.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDetailFetcher.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceIntentConsts.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceAutocompleteFragment.java, mapzen-places-api/src/test/java/com/mapzen/places/api/AutocompletePredictionBufferTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/AutocompleteDetailFetchListenerTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlaceAutocompletePresenterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/TestPlaceDetailFetcher.java, samples/mapzen-places-api-sample/build.gradle, samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/AutocompleteDemoActivity.java, samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/GeoDataApiActivity.java, samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/PlacePickerDemoActivity.java, samples/mapzen-places-api-sample/src/main/res/layout/activity_autocomplete.xml, samples/mapzen-places-api-sample/src/main/res/values/strings.xml
This PR adds support for fetching details about a `Place` when using the Autocomplete API. It also allows setting a `BoundingBox` when launching this UI. The LOST library has been updated to make `Status` objects `Parcelable`, this PR now passes them back in the `Intent` data. Lastly, this adds support for filtering results using the `AutocompleteFilter` object.
'OnPlaceDetailsFetchedListener' interface has been updated to pass a `Place` object back. `AutocompleteDetailFetchListener` has been added to handle notifying the controller when place details are successfully fetched (or fail to be fetched). `AutocompleteFilter` has been built out and and made functional. `PeliasFilterMapper` handles mapping `AutocompleteFilter` filters to parameters accepted by `Pelias`.
=> Autocomplete pt3

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompletePresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceAutocomplete.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceAutocompleteFragment.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlaceAutocompletePresenterTest.java, samples/mapzen-places-api-sample/src/main/AndroidManifest.xml
When neither `PlaceAutocomplete.IntentBuilder#setBoundsBias` nor `PlaceAutocompleteFragment#setBoundsBias` have  been set, we should fallback to retrieving the device's location to limit results (if the user has requested location permissions), otherwise don't restrict results.
- Add `LostApiClient` property to `PlaceAutocompletePresenter`
- Fetch device's last known location if client is connected
- Update javadocs to notify developers that they need to request coarse location updates if bounds bias not set
- Add coarse location permission to place sample app manifest
Closes #255
=> Fallback to Device Location

build.gradle, samples/mapzen-android-sdk-sample/build.gradle
Adds custom build and install gradle tasks
Adds custom gradle tasks for `installSdk`, `installPlaces`, `installSdkDemo`, and `installPlacesDemo` to ensure dependencies are built in the proper order and installed to the local maven repository. These tasks also run all tests and codestyle checks associated with the relevant modules.
=> Adds custom build and install gradle tasks

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java
Overrides default behavior so that no search is executed and keyboard is dismissed when the search key is pressed
- Sets a `SearchSubmitListener` on the `PeliasSearchView` to customize behavior when search key pressed
Closes #254
=> Better search submit handling for Places autocomplete

circle.yml, core/src/main/java/com/mapzen/android/graphics/MapFragment.java, core/src/main/java/com/mapzen/android/graphics/MapView.java, core/src/main/res/layout/mz_fragment_map_classic.xml, core/src/main/res/layout/mz_view_map_classic.xml, core/src/main/res/values/attrs.xml, core/src/main/res/values/dimens.xml, core/src/test/java/com/mapzen/android/graphics/MapFragmentTest.java, core/src/test/java/com/mapzen/android/graphics/MapViewTest.java, core/src/test/java/com/mapzen/android/graphics/TestLayoutInflater.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/BasicMapzenActivity.java, samples/mapzen-android-sdk-sample/src/main/res/layout/activity_spinner.xml
Provides two configuration options for map control overlays (find me, compass, and zoom buttons). "SDK" mode configures the map controls similar to other popular SDKs. "Classic" mode configures the map controls the way the Mapzen SDK (and Eraser Map) have worked in the past.
Configuration of the overlay controls is set using new custom view attributes on either `MapView` or `MapFragment`.
Based on this attribute one of two layout files is loaded when the view is inflated.
"SDK" layout mode is the new default mode.
=> Provide overlay manager configuration options

core/src/main/java/com/mapzen/android/core/ApiKeyConstants.java, core/src/main/java/com/mapzen/android/graphics/MapView.java, docs/getting-started.md, docs/search.md, docs/turn-by-turn.md, samples/mapzen-android-sdk-sample/src/main/res/values/mapzen.xml, samples/mapzen-places-api-sample/src/main/res/values/mapzen.xml
Makes API key resource name Mapzen-specific and updates documentation around how to setup API key to include more specific examples
- "api_key" -> "mapzen_api_key" when set via `mapzen.xml`
- Update javadocs and `docs/` files
- Update sample apps
Closes #249
=> 249 api key rename

mapzen-places-api/src/main/java/com/mapzen/places/api/Place.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasCallbackHandler.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasFeatureToPlaceConverter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasFilterMapper.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasLayerConsts.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasLayerToPlaceTypeConverter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasPlaceDetailFetcher.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompletePresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceImpl.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PointToBoundsConverter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlacePicker.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PeliasCallbackHandlerTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PeliasFeatureToPlaceConverterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PeliasLayerToPlaceTypeConverterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PeliasPlaceDetailFetcherTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PointToBoundsConverterTest.java, samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/PlacePickerDemoActivity.java
This adds support for mapping `Pelias` layer strings returned from the server to `Place#placeType` ints expected by developers. It also refactors (and adds tests for) some of the `Place` fetch-related classes. [place-type-tests.txt](https://github.com/mapzen/android/files/733576/place-type-tests.txt) lists the `Pelias` http request I made, the name of the corresponding `GooglePlace` I selected, and the values I observed that place object to have. 
- Adds `PeliasLayerConsts` to represent all possible layers that the server can return
- Refactors `PeliasFilterMapper`to use these layer values
- Add supported place types to `Place` interface
- Adds `PeliasLayerToPlaceTypeConverter` to handle converting layers returned by server into recognized `Place` type values. Adds test coverage for this …
=> Support Place placeType

build.gradle, circle.yml, core/build.gradle, gradle/wrapper/gradle-wrapper.properties, mapzen-android-sdk/build.gradle, mapzen-places-api/build.gradle, samples/mapzen-android-sdk-sample/build.gradle, scripts/deploy-android-sdk-sample-app.sh, scripts/deploy-places-api-sample-app.sh, scripts/deploy-samples.sh, scripts/publish-docs.sh
Improves build performance on Circle CI. Reduces build time by 1-2 min for dev builds and 4-5 min for full master builds (includes sample apps). Prevents OOM errors on Circle CI container.
* Updates Gradle options to limit memory use and dump heap on OOM error.
* Runs unit tests against debug build only and reduces console output.
* Upgrades Gradle to version 3.3 and gradle-android-maven-plugin to version 1.5.
* Adds `--configure-on-demand` and `-PdisablePreDex` options to circle.yml.
* Runs tests for each module in parallel using 3 Circle CI containers instead of 1.
* Archives sample app APKs on Circle CI and deploys to AWS on release build only.
* Publishes documentation to Mapzen website on release build only.
* Installs `core` module to local .m2 repo before resolving dependencies.
* …
=> Improve build performance

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasPlaceDetailFetcher.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDetailFetcher.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PeliasPlaceDetailFetcherTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/TestPlaceDetailFetcher.java
Replaces reverse geocode and string match on title with a constructed Pelias gid and /place endpoint when a map POI is selected in the place picker widget.
If tile properties contains an `area` for the selected POI then the Pelias gid is constructed using "openstreetmap:venue:**way**:[ID]" otherwise uses "openstreetmap:venue:**node**:[ID]" to fetch details from the /place endpoint.
Fixes #295
=> Updates place picker fetch details logic

circle.yml, core/build.gradle, mapzen-android-sdk/build.gradle, mapzen-places-api/build.gradle, release-checklist.md, scripts/deploy-android-sdk-sample-app.sh, scripts/deploy-places-api-sample-app.sh, scripts/deploy-samples.sh, scripts/deploy-staging.sh, scripts/publish-docs.sh
Updates build config to deploy release AARs directly to Maven Central from Circle CI when a new release tag is pushed to GitHub.
* Adds `release` deployment config to `circle.yml`.
* Adds `deploy-staging.sh` to build, sign, and deploy release AARs to Sonatype staging repository.
* Deploys sample apps to s3 and triggers documentation build on release only.
* Removes `afterReleaseBuild.dependsOn uploadArchives` given we don't want to upload artifacts from the local build only when its run on Circle CI.
=> Deploy release directly from Circle CI

mapzen-android-sdk/build.gradle, mapzen-places-api/build.gradle
Use dynamic `version` property when declaring core module dependency in sdk and places modules.
Update `mapzen-android-sdk/build.gradle` and `mapzen-places-api/build.gradle` to use dynamic version number from `gradle.properties` when including `mapzen-core` dependency.
=> Use dynamic version property for core module dependency

mapzen-android-sdk/build.gradle, mapzen-places-api/build.gradle
Use a project dependency for `core` in the sdk and places modules.
Replace core module remote dependency with project dependency in sdk and places modules. This will not replace needing to deploy the `mapzen-core` module to maven central but rather should make local development workflow simpler and resolve build issues on Circle CI when version number is updated.
Also transitive dependencies seem to get resolved correctly for the core module when a snapshot is deployed locally now that the `gradle-release` plugin config has been updated.
=> One more try using project dependency for core module

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerViewController.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/TestPlacePickerController.java
My location layer should be disabled when the `PlacePickerActivity` is no longer visible on the screen (i.e. paused or finished).
This resolves two issues:
1. When the place picker activity was finished location services would not be properly shutdown and the app would leak a service connection to the Lost fused location service (#301).
2. This prevents location services from running hot when the place picker activity is in the background. Location updates are only needed when the place picker is visible on the screen and the user is in the process of selecting a place.
* Disable location services in `PlacePickerActivity#onPause()`.
* Re-enable location services in `PlacePickerActivity#onResume()`.
Fixes #301
=> Disable location layer when place picker is paused or finished

build.gradle, docs/javadoc.md, release-checklist.md
Enables Javadoc build task. Adds documentation page with links to javadoc hosted on github pages.
* Enable javadoc tasks in root project `build.gradle`
* Adds `docs/javadoc.md`
* Updates release notes
=> Deploy javadoc

core/src/main/java/com/mapzen/android/graphics/MapFragment.java, core/src/main/java/com/mapzen/android/graphics/MapInitializer.java, core/src/main/java/com/mapzen/android/graphics/MapView.java, core/src/test/java/com/mapzen/android/graphics/MapInitializerTest.java, core/src/test/java/com/mapzen/android/graphics/MapViewTest.java
Allows developer to set language for map labels when creating the map. Otherwise uses device default language for map labels. Previously each label was rendered in its "local" language which led to a mix of languages getting rendered.
Developers can now set the map label language via `getMapAsync(...)` on both `MapView` and `MapFragment`. This `Locale` is used to set the stylesheet global variable `global.ux_language`.
If no language is set `Locale.getDefault()` is used.
**Example**
```java
mapFragment.getMapAsync(new BubbleWrapStyle(), Locale.CHINESE, callback);
```
Fixes #290
=> Set map label language

mapzen-android-sdk/src/main/java/com/mapzen/android/routing/MapzenRouter.java, mapzen-android-sdk/src/test/java/com/mapzen/android/routing/MapzenRouterTest.java
Exposes wrapper method to set language via `MapzenRouter`.
Adds `MapzenRouter#setLanguage(Router.Language language)` using On the Road language codes.
Updated On the Road to use default Locale when none is specified here:
https://github.com/mapzen/on-the-road_android/pull/108
Closes #291
=> Exposes method to set language via `MapzenRouter`

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java
Prevents full screen extracted UI when editing search view text in landscape mode.
Adds flag to prevent full screen edit text UI so autocomplete results are visible. Previously all results were obscured by soft keyboard and large edit text box.
Fixes #325
=> Should not extract search IME UI in landscape mode

core/src/main/java/com/mapzen/android/graphics/MapView.java, core/src/main/java/com/mapzen/android/graphics/MapzenMap.java, core/src/test/java/com/mapzen/android/graphics/MapViewTest.java, core/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java, core/src/test/java/com/mapzen/android/graphics/TestMapController.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/BasicMapzenActivity.java
This change set fixes two issues:
1. The map position and zoom level were not properly set when the place picker map is first initialized.
2. If the user panned or zoomed the place picker map the view state would not be maintained on device rotation.
* Forward MapView#onDestroy() events to MapzenMap
* MapzenMap saves current map position, zoom, rotation, and tilt when destroyed
* The place picker map is not be re-initailized after device rotation but rather restored to the prior state.
* Adds a default zoom level of 15 to use when making initial map position and zoom calculations.
Fixes #326
=> Place picker map position

circle.yml, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDialogFragment.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceStore.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/TestPlacePickerController.java, samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/PlacePickerDemoActivity.java
Properly handle place picker dialog on configuration change so state is persisted and dialog is not leaked.
* Converts place picker dialog from standalone `AlertDialog` to a `DialogFragment` to maintain view state.
* Add `PlaceStore` singleton to persist current selection data through configuration change when `PlacePickerPresenter` is destroyed and recreated along with `PlacePickerActivity`.
* Updates sample app to (naively) handle configuration change by preventing launching another instance of the place picker if one is already active.
Fixes #324
=> Handle place picker dialog on configuration change

core/src/main/java/com/mapzen/android/graphics/MapView.java
Fixed crash when mapzenMap field was not set in MapView instance. This caused crash in my app when `MapzenMap` wasn't initialized because my app uses Google Maps API and Mapzen Android SDK and only one of them can be active at a time causing that one of them won't be initialized at app startup.
Add null pointer check to `onDestroy()` method in `MapView` class.
=> Fixed crash when mapzenMap field was not set in MapView instance

core/src/main/java/com/mapzen/android/graphics/OverlayManager.java
With help of Leak Canary https://github.com/square/leakcanary I have found some memory leaks inside Mapzen Android SDK in OverlayManager.
I am not sure whether creating new LostApiClient inside OverlayManager constructor instead of using sharedClient is a correct solution, but it is very dangerous to set Context into static field variable as it will always leak when not handled properly.
=> Fixed some Lost memory leaks

core/build.gradle, core/src/main/java/com/mapzen/android/core/MapzenManager.java, core/src/main/java/com/mapzen/android/graphics/OverlayManager.java, core/src/main/java/com/mapzen/android/location/LocationFactory.java, core/src/test/java/com/mapzen/android/core/MapzenManagerTest.java, core/src/test/java/com/mapzen/android/graphics/MapInitializerTest.java, core/src/test/java/com/mapzen/android/location/LocationFactoryTest.java, mapzen-places-api/src/test/java/com/mapzen/android/lost/internal/FusedApiServiceUpdater.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlaceAutocompletePresenterTest.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/BasicMapzenActivity.java
Fixes memory leaks!
- Upgrades to LOST `2.3.0-SNAPSHOT` which always uses the application `Context` when creating new `LostApiClient`s
- `LocationFactory` is simplified and improved. It does not keep a static reference to a `Context` and instead vends a new client only if one doesn't already exist
- Static inner class in `OverlayManager` now uses a weak reference of `OverlayManager`
- Migrates `MapzenManager` to use the application context
- Updates tests for new LOST version and for `Context` updates
- Small cleanup in basic SDK sample `Activity`
Closes #338
=> Fix Memory Leaks

config/checkstyle/checkstyle-suppressions.xml, core/src/main/java/com/mapzen/android/graphics/GraphicsModule.java, core/src/main/java/com/mapzen/android/graphics/MapInitializer.java, core/src/main/java/com/mapzen/android/graphics/MapzenMap.java, core/src/main/java/com/mapzen/android/graphics/SceneUpdateManager.java, core/src/test/java/com/mapzen/android/graphics/MapInitializerTest.java, core/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java, core/src/test/java/com/mapzen/android/graphics/SceneUpdateManagerTest.java, core/src/test/java/com/mapzen/android/graphics/TestMapView.java
This PR updates `MapzenMap#setStyle` so that it reconfigures global scene updates (such as api key and locale) when a new style is loaded
Closes #363
=> Improve Style Switching

core/src/main/java/com/mapzen/android/graphics/MapInitializer.java, core/src/main/java/com/mapzen/android/graphics/MapStateManager.java, core/src/main/java/com/mapzen/android/graphics/MapzenMap.java, core/src/main/java/com/mapzen/android/graphics/SceneUpdateManager.java, core/src/test/java/com/mapzen/android/graphics/MapInitializerTest.java, core/src/test/java/com/mapzen/android/graphics/MapStateManagerTest.java, core/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java, core/src/test/java/com/mapzen/android/graphics/SceneUpdateManagerTest.java, core/src/test/java/com/mapzen/android/graphics/SceneUpdateMatcher.java, core/src/test/java/com/mapzen/android/graphics/SceneUpdatesMatcher.java, samples/mapzen-android-sdk-sample/src/main/AndroidManifest.xml, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/OverlayActivity.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/SampleDetailsList.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/SwitchStyleActivity.java, samples/mapzen-android-sdk-sample/src/main/res/layout/activity_overlay.xml, samples/mapzen-android-sdk-sample/src/main/res/values/strings.xml
Adds support for transit,bike, and path overlays provided via global stylesheet variables.
- Adds methods to `MapzenMap` to update these overlays individually or in bulk
- Transit and bike overlays are disabled by default, path overlay is enabled (to be consistent with house stylesheets)
- Persists overlay state on rotation
- Adds an `OverlayActivity` example to show off this functionality in the sample app
- Small UI and optimizations made to `SwitchStyleActivity` example
Closes #244
=> Add map overlays

core/src/main/java/com/mapzen/android/graphics/OverlayManager.java, core/src/test/java/com/mapzen/android/graphics/OverlayManagerTest.java
Uses stable API to access UI elements instead of directly calling `findViewById`
Closes #242
=> Use getFindMe api

samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/FeaturePickListenerActivity.java
Updates the `FeaturePickActivity` to not show an empty `Toast`. Currently, no `Toasts` are shown because the properties returned by the listener are always empty. This bug will be resolved ~in a future version of Tangram~ when the stylesheets are updated https://github.com/mapzen/android/issues/384 and the example is changed to use non-point style MapData https://github.com/mapzen/android/issues/385
Closes #314
=> Dont show empty toast in feature pick example

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasCallbackHandler.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasFeatureConverter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasLayerToPlaceTypeConverter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompletePresenter.java, mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerViewController.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PeliasFeatureConverterTest.java, mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlaceAutocompletePresenterTest.java
To handle optional `gid` values, this code updates the `Places` API to simply return a `Place` object from the current `Feature` instead of trying to fetch details given an empty `gid`
- Refactors code to create a `Place` and details string into the same `PeliasFeatureConverter` object to centralize logic
- Updates documentation
- Adds more test coverage for optional `gid`
Closes #388
=> Return Place from Feature if no gid present

core/src/main/java/com/mapzen/android/graphics/FeaturePickListener.java, core/src/main/java/com/mapzen/android/graphics/LabelPickListener.java, core/src/main/java/com/mapzen/android/graphics/MarkerPickListener.java
This makes the docs explicit about which objects will receive a callback via the `FeaturePickListener`
Closes #386
=> Update feature pick listener docs

docs/getting-started.md, docs/search.md, docs/turn-by-turn.md
These changes are part of https://github.com/mapzen/documentation/issues/310
This updates the placeholder text to use your-mapzen-api-key (please make sure I didn't accidentally remove required quotation marks or anything like that) so it can be automatically replaced when signed in.
I also deleted some text that describes how to use the placeholder text (like replace it with your real key) because the key is already replaced when signed in, and the pop-up over the text will be the call to action for users who are not signed in.
There were also a few minor style (change "we" to you or third-party) and typo issues that I happened to see.
=> Update placeholder text, few links, typos

config/checkstyle/checkstyle-suppressions.xml, core/src/main/java/com/mapzen/android/graphics/GraphicsModule.java, core/src/main/java/com/mapzen/android/graphics/MapInitializer.java, core/src/main/java/com/mapzen/android/graphics/MapReadyInitializer.java, core/src/main/java/com/mapzen/android/graphics/MapzenMap.java, core/src/main/java/com/mapzen/android/graphics/internal/StyleStringGenerator.java, core/src/main/java/com/mapzen/android/graphics/model/BitmapMarker.java, core/src/main/java/com/mapzen/android/graphics/model/BitmapMarkerFactory.java, core/src/main/java/com/mapzen/android/graphics/model/BitmapMarkerManager.java, core/src/main/java/com/mapzen/android/graphics/model/BitmapMarkerOptions.java, core/src/main/java/com/mapzen/android/graphics/model/MarkerManager.java, core/src/main/java/com/mapzen/android/graphics/model/MarkerOptions.java, core/src/test/java/com/mapzen/android/graphics/MapInitializerTest.java, core/src/test/java/com/mapzen/android/graphics/MapReadyInitializerTest.java, core/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java, core/src/test/java/com/mapzen/android/graphics/TestMapView.java, core/src/test/java/com/mapzen/android/graphics/internal/StyleStringGeneratorTest.java, core/src/test/java/com/mapzen/android/graphics/model/BitmapMarkerManagerTest.java, core/src/test/java/com/mapzen/android/graphics/model/BitmapMarkerOptionsTest.java, core/src/test/java/com/mapzen/android/graphics/model/BitmapMarkerTest.java, core/src/test/java/com/mapzen/android/graphics/model/MarkerManagerTest.java, core/src/test/java/com/mapzen/android/graphics/model/MarkerOptionsTest.java, samples/mapzen-android-sdk-sample/src/main/AndroidManifest.xml, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/CustomMarkerActivity.java, samples/mapzen-android-sdk-sample/src/main/res/layout/activity_custom_marker.xml
This PR uses `SceneLoadListener` to restore markers on scene updates, including scene updates which occur because of orientation changes. This code doesn't check `sceneId` in the listener callback because we always want to restore markers when the scene is ready after any update. It also doesn't check `sceneError` because the sdk doesn't have first class support for loading custom scenes and ensures that all house styles work with the apis we provide.
- Adds `SceneLoadListener` to `MapzenMap`
- Adds restoration handling to `MarkerManager`
- Updates `MarkerOptions` to include all `BitmapMarker` properties
- Updates `BitmapMarker` to provide property getters
- Migrates `StyleStringGenerator` and `MarkerManager` to be singletons
- Updates and adds test coverage
- Updates custom marker …
=> Restore Markers

config/checkstyle/checkstyle-suppressions.xml, core/src/main/java/com/mapzen/android/core/GenericHttpHandler.java, core/src/main/java/com/mapzen/android/graphics/MapzenMap.java, core/src/main/java/com/mapzen/android/search/MapzenSearch.java, core/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java, core/src/test/java/com/mapzen/android/search/MapzenSearchTest.java, mapzen-android-sdk/src/main/java/com/mapzen/android/routing/MapzenRouter.java, mapzen-android-sdk/src/main/java/com/mapzen/android/routing/MapzenRouterHttpHandler.java, mapzen-android-sdk/src/test/java/com/mapzen/android/routing/MapzenRouterHttpHandlerTest.java, mapzen-android-sdk/src/test/java/com/mapzen/android/routing/MapzenRouterTest.java, mapzen-android-sdk/src/test/java/com/mapzen/valhalla/TestHttpHandlerHelper.java
This is the first of two PRs needed to bring first class support for providing custom http headers and parameters to search, routing, and tile requests. This work adds `MapzenSearch#setHttpHandler(MapzenSearchHttpHandler )`, `MapzenRouter#setHttpHandler(MapzenRouterHttpHandler )`, and `MapzenMap#setHttpHandler(MapzenMapHttpHandler )` methods.
- Adds top level APIs to set custom http parameters and headers
- Adds relevant test coverage
- Adds SDK `LogLevel` enum for mapping to internal implementation log level (future PR will provide ability to set log level on search and map handlers as well https://github.com/mapzen/android/issues/445)
- Updates `MapzenRouterHttpHandler` to allow setting base url and log level
A follow up PR will provide support for pulling the API key from …
=> Provide top level methods to set custom http handlers

samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/CustomMarkerActivity.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/LabelPickListenerActivity.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/OverlayActivity.java, samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/SimpleStyleSwitcherActivity.java
A recent PR (https://github.com/mapzen/android/pull/465) broke the samples for custom markers and overlays. This creates a new class for those samples to extend from which provides a spinner populated with map styles and handles updating the map when one is selected
- Adds new `Activity` for custom marker and overlay samples to extend from
- Fixes NPE in `LabelPickListenerActivity` observed when name property not present
=> Fix Custom Marker and Overlay Samples

core/src/main/java/com/mapzen/android/graphics/MapInitializer.java, core/src/main/java/com/mapzen/android/graphics/MapView.java, core/src/main/java/com/mapzen/android/graphics/MapzenMap.java, core/src/test/java/com/mapzen/android/graphics/MapInitializerTest.java, core/src/test/java/com/mapzen/android/graphics/MapViewTest.java, core/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java
Resets the `setSceneLoadListener` when the `MapView` is destroyed
- Adds more test coverage
Closes #471
=> Remove listener when map view destroyed

core/build.gradle
Upgrades Lost dependency from 3.0.0 to 3.0.3. 
This upgrade includes stability and bug fixes. It also removes (https://github.com/mapzen/lost/releases/tag/lost-3.0.2) throwing of `IllegalStateException`s and instead logs the `RemoteException` thrown (more work will be done to fully support error handling https://github.com/mapzen/lost/issues/229)
Closes #469
=> Lost 3.0.3

README.md, build.gradle, config/checkstyle/checkstyle.xml, core/build.gradle, gradle/wrapper/gradle-wrapper.properties, mapzen-android-sdk/build.gradle, mapzen-android-sdk/src/main/java/com/mapzen/android/routing/MapzenRouter.java, mapzen-places-api/build.gradle, samples/mapzen-android-sdk-sample/build.gradle, samples/mapzen-places-api-sample/build.gradle, samples/mapzen-sample/build.gradle
Upgrades to Gradle 4.1/Gradle Plugin 3.0.0 for use with Android Studio 3.0
- Follows the migration guide to take advantage of build performance increases (https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html)
- Updates README to note that developers who wish to build the SDK from source will have to revert build scripts to use deprecated methods
- Removes deprecated checkstyle rule (https://github.com/checkstyle/checkstyle/issues/473)
Closes #504
=> Upgrade Gradle

core/src/main/java/com/mapzen/android/graphics/GraphicsModule.java, core/src/main/java/com/mapzen/android/graphics/MapFragment.java, core/src/main/java/com/mapzen/android/graphics/MapInitializer.java, core/src/main/java/com/mapzen/android/graphics/MapView.java, core/src/main/java/com/mapzen/android/graphics/PersistDataManagers.java, core/src/test/java/com/mapzen/android/graphics/MapInitializerTest.java
Internal marker manager singletons are now scoped to map instances allowing support for multiple `MapzenMap` instances within a single application. 
- Adds new parameter to pass a unique map id
- If no parameter is passed, the global map is used (same behavior as before)
Closes #436
=> Multiple Map Instances
