mapzen/android

library/src/main/java/com/mapzen/android/MapFragment.java
library/src/main/java/com/mapzen/android/MapInitializer.java
library/src/main/java/com/mapzen/android/MapView.java
library/src/main/java/com/mapzen/android/MapzenMap.java
library/src/main/java/com/mapzen/android/OverlayManager.java
library/src/test/java/com/mapzen/android/MapzenMapTest.java
library/src/test/java/com/mapzen/android/OverlayManagerTest.java
library/src/test/java/com/mapzen/android/TestMapView.java
sample/src/main/java/com/mapzen/android/sample/BasicMapzenActivity.java
sample/src/main/java/com/mapzen/android/sample/MarkerMapzenActivity.java
sample/src/main/java/com/mapzen/android/sample/PolygonMapzenActivity.java
sample/src/main/java/com/mapzen/android/sample/PolylineMapzenActivity.java

Adds wrapper methods to `MapzenMap` to simplify API used by client apps.

Mapzen map methods

---

.gitmodules
library/src/main/java/com/mapzen/android/MapFragment.java
library/src/main/java/com/mapzen/android/MapInitializer.java
library/src/main/java/com/mapzen/android/MapStyleToSceneFile.java
library/src/main/java/com/mapzen/android/MapView.java
library/src/main/java/com/mapzen/android/MapzenMap.java
library/src/main/java/com/mapzen/android/OverlayManager.java
library/src/main/java/com/mapzen/android/model/MapStyle.java
library/src/test/java/com/mapzen/android/MapInitializerTest.java
library/src/test/java/com/mapzen/android/MapViewTest.java
library/src/test/java/com/mapzen/android/OverlayManagerTest.java
library/src/test/java/com/mapzen/android/TestMapController.java
library/src/test/java/com/mapzen/android/TestMapView.java
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/mapzen/android/sample/SampleDetailsList.java
sample/src/main/java/com/mapzen/android/sample/SwitchStyleActivity.java
sample/src/main/res/layout/activity_main.xml
sample/src/main/res/layout/activity_sample_mapzen.xml
sample/src/main/res/layout/activity_switch_style.xml
sample/src/main/res/values/strings.xml

Still need to update example to show how to re-add markers/lines after style change. Also will need to update outdoor style to have new standardized names & marker/line styles when new bubble-wrap style fixes get merged.
Closes #48

Multiple stylesheets

---

docs/basic-functions.md
docs/current-location.md
docs/getting-started.md
docs/polygon.md
docs/polyline.md

working on https://github.com/mapzen/android/issues/58

MapFragment fixing

---

library/src/main/java/com/mapzen/android/MapView.java
library/src/main/res/layout/view_map.xml
library/src/main/res/values/strings.xml

Add attribution text to MapView

---

docs/installation.md

Update install docs

---

docs/current-location.md
library/src/main/java/com/mapzen/android/MapzenMap.java
library/src/main/java/com/mapzen/android/OverlayManager.java
library/src/test/java/com/mapzen/android/MapzenMapTest.java
library/src/test/java/com/mapzen/android/OverlayManagerTest.java
sample/src/main/java/com/mapzen/android/sample/BasicMapzenActivity.java

Add method to query location enabled & stop in onPause

---

library/build.gradle

https://github.com/tangrams/tangram-es/releases/tag/0.2.2-android

Upgrades Tangram to version 0.2.2

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Upgrades gradle distro to 2.10 and android plugin to 2.1

---

library/src/main/res/drawable/bg_white_gray_border.xml

Fixes crash on devices running api 20 and lower
Closes #101

Remove recursive call to layout file

---

library/build.gradle
library/src/main/AndroidManifest.xml
library/src/main/res/values/strings.xml
sample/src/main/AndroidManifest.xml

- Adds on-the-road as dependency of sdk
- Removes unnecessary label from library
- Updates sample app's label to read resource from sample app
Closes #89

Add on-the-road and remove unnecc label from library

---

library/src/main/res/layout/mz_view_map.xml
library/src/main/res/values/dimens.xml
library/src/main/res/values/strings.xml

Adds width, height, and margin values to dimens.xml.
Also adds content description.

Adjust margins on find me button

---

library/build.gradle

This version removes all dependencies on android APIs
Closes #91

Update on-the-road to 0.8.2-SNAPSHOT

---

library/build.gradle

Tangram 0.3.1

---

library/src/main/java/com/mapzen/android/MapzenRouter.java
library/src/test/java/com/mapzen/android/MapzenRouterTest.java

https://github.com/mapzen/on-the-road/blob/master/src/main/java/com/mapzen/valhalla/Router.kt#L14
Allows to be stored/read interchangebly from shared preferences.
Fixes https://github.com/mapzen/eraser-map/issues/619

Updates Mapzen distance unit enum string values to match on-the-road.

---

library/build.gradle

Closes #124 
Fixes https://github.com/mapzen/eraser-map/issues/597
Fixes https://github.com/mapzen/eraser-map/issues/629
Fixes https://github.com/mapzen/eraser-map/issues/633

Upgrades Tangram to version 0.3.2

---

library/src/main/java/com/mapzen/android/MapzenRouter.java
library/src/test/java/com/mapzen/android/MapzenRouterTest.java

Depends on: https://github.com/mapzen/on-the-road/pull/77

Add multimodal routing support

---

library/build.gradle

- Add as string resource so that it can be read in client applications

Add string resource for tangram version

---

library/build.gradle

Add submodule check in library build.gradle

---

sample/README.md

Updates README for turn by turn key, submodules, and installation

---

.gitmodules
library/src/main/java/com/mapzen/android/MapzenMap.java
library/src/main/java/com/mapzen/android/OverlayManager.java
library/src/main/java/com/mapzen/android/model/CinnabarStyle.java
library/src/main/java/com/mapzen/android/model/RefillStyle.java
library/src/test/java/com/mapzen/android/MapzenMapTest.java
library/src/test/java/com/mapzen/android/OverlayManagerTest.java

- Support drawing transit route line & transit stations
- Updates cinnabar and refill styles to use `more-labels` version

Add transit route line and station icon

---

library/build.gradle

Upgrade Pelias Android SDK to release version 0.7.2

Pelias Android SDK v0.7.2

---

library/build.gradle

Bumps tangram version and upgrades to corresponding bubble-wrap 4.1.1 release
Closes #162

Upgrade to tangram-0.4.2

---

.gitmodules
library/src/main/java/com/mapzen/android/graphics/model/WalkaboutStyle.java
sample/src/main/java/com/mapzen/android/sample/SwitchStyleActivity.java
sample/src/main/res/values/strings.xml

Adds Walkabout style

---

circle.yml
library/build.gradle
sample/build.gradle

Update build tools and support library
- Update `buildToolsVersion` to 24.0.3
- Update `com.android.support:appcompat-v7` to 24.2.1
- Update `compileSdkVersion` to 24
- Update `circle.yml` build tools version dependency
Closes #172

Update build tools, support library, and compile sdk

---

library/src/main/java/com/mapzen/android/graphics/MapView.java
sample/build.gradle
sample/src/main/java/com/mapzen/android/sample/MapzenSearchViewActivity.java
sample/src/main/java/com/mapzen/android/sample/RouterActivity.java
scripts/deploy-sample-app.sh

Replace service-specific `BuildConfig` keys with single api key
Closes #199

Single API key for Sample App

---

library/build.gradle

Bump lost and on the road dependencies
Lost 2.1.0
On the Road 1.1.0

Bump lost and on the road

---

library/build.gradle

Upgrade to Lost 2.1.1
Fixes current location and find me not showing
Closes #208

Lost 2.1.1

---

library/build.gradle

Upgrade Tangram to version 0.4.3
Closes #211 
Fixes #207

Upgrade Tangram 0.4.3

---

library/build.gradle

Upgrade Lost to latest snapshot to test service crash fix
https://github.com/mapzen/lost/pull/133

Use Lost snapshot to test service crash fix

---

library/build.gradle
library/src/main/java/com/mapzen/android/graphics/MapInitializer.java
library/src/main/java/com/mapzen/android/graphics/MapzenMap.java
library/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java
library/src/test/java/com/mapzen/android/graphics/TestMapController.java
library/src/test/java/com/mapzen/android/graphics/TestMapView.java

Upgrades Tangram ES to release version 0.4.5
https://github.com/tangrams/tangram-es/releases/tag/0.4.5-android

Upgrades Tangram ES to release version 0.4.5

---

config/checkstyle/checkstyle-suppressions.xml
core/build.gradle
mapzen-places-api/src/main/AndroidManifest.xml
mapzen-places-api/src/main/java/com/mapzen/places/api/LatLng.java
mapzen-places-api/src/main/java/com/mapzen/places/api/LatLngBounds.java
mapzen-places-api/src/main/java/com/mapzen/places/api/Place.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/AutocompletePendingResult.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/OnPlaceDetailsFetchedListener.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasPlaceDetailFetcher.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDetailFetcher.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceImpl.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenter.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerViewController.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/ui/PlacePickerActivity.java
mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlacePicker.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/TestPlaceDetailFetcher.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/TestPlacePickerController.java
samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/PlacePickerDemoActivity.java
samples/mapzen-places-api-sample/src/main/res/layout/place_picker_demo.xml
samples/mapzen-places-api-sample/src/main/res/values/mapzen.xml
samples/mapzen-places-api-sample/src/main/res/values/strings.xml

This PR adds support for the `PlacePicker` api which allows the user to select a place on the map and get details about it. It also adds an activity to demonstrate how to use the new api.
I created an interface `PlaceDetailFetcher` to abstract the source we use to fetch details. Right now this is Pelias but will soon be changed to WOF.
Closes #197

Place picker details

---

core/build.gradle
mapzen-places-api/src/main/java/com/mapzen/places/api/AutocompleteFilter.java
mapzen-places-api/src/main/java/com/mapzen/places/api/Place.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/AutocompleteDetailFetchListener.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/AutocompletePendingResult.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/FilterMapper.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/OnPlaceDetailsFetchedListener.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasFilterMapper.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PeliasPlaceDetailFetcher.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteController.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompletePresenter.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteView.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceDetailFetcher.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceIntentConsts.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenter.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java
mapzen-places-api/src/main/java/com/mapzen/places/api/ui/PlaceAutocompleteFragment.java
mapzen-places-api/src/test/java/com/mapzen/places/api/AutocompletePredictionBufferTest.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/AutocompleteDetailFetchListenerTest.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlaceAutocompletePresenterTest.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/TestPlaceDetailFetcher.java
samples/mapzen-places-api-sample/build.gradle
samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/AutocompleteDemoActivity.java
samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/GeoDataApiActivity.java
samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/PlacePickerDemoActivity.java
samples/mapzen-places-api-sample/src/main/res/layout/activity_autocomplete.xml
samples/mapzen-places-api-sample/src/main/res/values/strings.xml

Clears fragment search view text
Depends on: https://github.com/mapzen/android/pull/246
Closes #252

Clear Search Text

---

core/src/main/java/com/mapzen/android/graphics/CompassView.java

Public constructor for `CompassView`
Fixes demo app crash on view inflation

Public constructor for `CompassView`

---

build.gradle

Upgrades Android Gradle plugin to version 2.2.3
Update root `build.gradle` file in the project

Upgrades Android Gradle plugin to version 2.2.3

---

circle.yml
core/build.gradle
mapzen-android-sdk/build.gradle
mapzen-places-api/build.gradle
samples/mapzen-android-sdk-sample/build.gradle
samples/mapzen-places-api-sample/build.gradle

Build tools 25.0.1

---

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlaceAutocompleteActivity.java

When the autocomplete list is scrolled the keyboard is now dismissed
Closes #275

Dismiss place autocomplete keyboard on scroll

---

mapzen-places-api/src/main/res/layout/place_fragment_map.xml
mapzen-places-api/src/main/res/layout/place_picker_activity.xml

Updates the places module to use a layout which configures `MapzenMap` to `classic` mode

Classic mode for places map fragment

---

README.md
docs/autocomplete-ui.md
docs/geodata-api.md
docs/getting-started-places.md
docs/installation-places.md
docs/place-detection-api.md
docs/place-picker-ui.md
samples/mapzen-places-api-sample/README.md
samples/mapzen-places-api-sample/src/main/java/com/mapzen/places/api/sample/PlacePickerDemoActivity.java

Adds documentation for Places API, updates existing Android SDK documentation, and adds README for Places Sample app
Closes #274 
We should probably wait to merge this until https://github.com/mapzen/android/issues/279 is completed

Add places documentation & update existing documentation

---

docs/getting-started-places.md
docs/getting-started.md

Update getting started docs including API keys, access to Tangram APIs, and sample apps.
* Document setting API key via `MapzenManager` class
* Update reference to Tangram docs

Update getting started docs

---

docs/index.md

Updates the index page to include information about the Places API

Add Places API Documentation

---

build.gradle
circle.yml
core/build.gradle
mapzen-android-sdk/build.gradle
mapzen-places-api/build.gradle

Update release config for multi-module project.
* Update pelias, lost, and on the road dependencies to release candidate versions
* Consolidate release plugin config into root project `build.gradle`
* Cache downloaded android sdk folders on Circle CI
* Add code to disable pre dex for CI builds to root `build.gradle`

Multi-module release config

---

core/build.gradle

Upgrades Tangram dependency to release version 0.5.0
https://github.com/tangrams/tangram-es/releases/tag/0.5.0-android

Upgrades Tangram dependency to release version 0.5.0

---

circle.yml

Removes CI core install to local maven repo
No longer needed with project dependencies

Removes CI core install to local maven repo

---

mapzen-android-sdk/build.gradle

Adds waypoints support to `MapzenRouter` contributed by @kkalera.
https://github.com/mapzen/on-the-road_android/pull/102
Update on the road to version 1.2.0-rc2.

Update on the road to version 1.2.0-rc2

---

core/build.gradle
mapzen-android-sdk/build.gradle

Use final release version of pelias, on-the-road, and lost.
Pelias Android SDK 1.1.0
On the Road 1.2.0
Lost 2.2.0

Use final release version of pelias, on-the-road, and lost

---

docs/autocomplete-ui.md
docs/places.md

Adds screenshots to places docs
Update autocomplete-ui.md and places.md
Fixes #313

Adds screenshots to places docs

---

.gitmodules

Use https instead of ssh for tron submodule

---

samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/PolygonMapzenActivity.java

Try zooming in out with and without this change to see what happens.

GeoJSON polygon should be closed

---

docs/lost/geofences.md
docs/lost/get-started.md
docs/lost/getting-started.md
docs/lost/last-known-location.md
docs/lost/location-settings.md
docs/lost/location-updates.md
docs/lost/mock-locations-routes.md

Adds lost docs
Will need to merge https://github.com/mapzen/documentation/pull/299 after this is merged
Closes #248

Add lost documentation

---

core/build.gradle

Updates to Pelias 1.2.0 release https://github.com/pelias/pelias-android-sdk/releases/tag/pelias-android-sdk-1.2.0
Closes #394

Pelias 1.2.0

---

core/build.gradle

https://github.com/mapzen/lost/releases/tag/lost-3.0.0
Closes #396

Lost 3.0.0

---

mapzen-android-sdk/build.gradle
mapzen-android-sdk/src/main/java/com/mapzen/android/routing/MapzenRouter.java
mapzen-android-sdk/src/test/java/com/mapzen/android/routing/MapzenRouterTest.java

https://github.com/mapzen/on-the-road_android/releases/tag/on-the-road-1.3.0
Closes #369

on-the-road 1.3.0

---

samples/mapzen-android-sdk-sample/src/main/java/com/mapzen/android/sdk/sample/FeaturePickListenerActivity.java

Updates `FeaturePickActivity` to use non-point `MapData` (polygon)
Closes #385

Update feature pick listener example with polygon

---

core/build.gradle

Upgrades from the release candidate to the official release
https://github.com/tangrams/tangram-es/releases/tag/0.8.0
Closes #435

Tangram 0.8.0 release

---

core/src/main/java/com/mapzen/android/graphics/MapzenMap.java
core/src/main/java/com/mapzen/android/graphics/OnStyleLoadedListener.java
core/src/test/java/com/mapzen/android/graphics/MapzenMapTest.java

Provides methods for setting `MapStyle` asynchronously.
- Adds new `OnStyleLoadedListener` to handle notifying client that the requested style finished loading
- Notifies listener of the latest scene to complete loading
- Adds test coverage
Closes #438

Async setStyle

---

mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerActivity.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenter.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacePickerPresenterImpl.java
mapzen-places-api/src/main/java/com/mapzen/places/api/internal/PlacesBubbleWrapStyle.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacePickerPresenterTest.java
mapzen-places-api/src/test/java/com/mapzen/places/api/internal/PlacesBubbleWrapStyleTest.java

Creates a new class `PlacesBubbleWrapStyle` for use with the Place Picker UI
- `PlacesBubbleWrapStyle` sets default label level to `11`
- Adds test coverage
Before:
After:

Places BubbleWrap style

---

build.gradle
circle.yml
core/build.gradle
mapzen-android-sdk/build.gradle
mapzen-places-api/build.gradle
samples/mapzen-android-sdk-sample/build.gradle
samples/mapzen-places-api-sample/build.gradle
samples/mapzen-sample/build.gradle

Updates to gradle plugin `2.3.3` and android build tools `26.0.2`

Update gradle plugin and build tools version

---

samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/activities/MainActivity.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/activities/PermissionActivity.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/controllers/MainController.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/models/Settings.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/presenters/MainPresenter.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/presenters/MainPresenterImpl.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/presenters/SettingsPresenterImpl.kt
samples/mapzen-sample/src/main/res/color/text_row_text.xml
samples/mapzen-sample/src/main/res/drawable/row_bg_normal.xml
samples/mapzen-sample/src/main/res/drawable/row_bg_selected.xml
samples/mapzen-sample/src/main/res/drawable/text_row_bg.xml
samples/mapzen-sample/src/main/res/layout/activity_main.xml
samples/mapzen-sample/src/main/res/layout/text_row.xml
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/TestMainController.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/presenters/MainPresenterTest.kt

Adds selection state to sample tokens.
- Other minor code cleanup fixes
Closes #494

Token selection state

---

samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/activities/MainActivity.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/controllers/MainController.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/fragments/BaseFragment.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/fragments/BasicMapFragment.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/fragments/RoutePinsFragment.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/fragments/RoutingFragment.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/models/MapSampleList.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/presenters/MainPresenterImpl.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/presenters/RoutingPresenter.kt
samples/mapzen-sample/src/main/java/mapzen/com/sdksampleapp/presenters/RoutingPresenterImpl.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/TestMainController.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/models/MapSampleListTest.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/models/MoreSampleListTest.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/models/RouteSampleListTest.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/models/SearchSampleListTest.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/presenters/MainPresenterTest.kt
samples/mapzen-sample/src/test/java/mapzen/com/sdksampleapp/presenters/RoutingPresenterTest.kt

Adds basic sample to map tab and clears map data/router singleton when new tab or sample selected
- Adds test coverage for new features
Closes #507

Add basic sample
